---
title: "assignmentweek4_myapp documentation"
author: "Eng"
date: "May 1, 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

This is an app created for Developing Data Products Coursera course Week 4 assignment. This app is about a map of Setapak area, in Kuala Lumpur, Malaysia. Users are allowed to select their preferred coordinate and show them on the map. Besides, there is also suggestion of facilities available at Setapak such as hospital, restaurant, service residency and shopping mall. 

## Selection

### Sliders

- Latitude 
- Longitude

which allow users to choose their preferred coordinates. The available latitude and longitude values cover the whole Setapak area.

## Selection (cont')

### Checkbox

- Hospital
- Restaurant
- Shopping Mall
- Service Residency

which allow users to choose suggestion of facilities that available at Setapak area.

## Map

Selected coordinate, as well as selection of suggestion (if any) will be shown on the map. 

Name of selected facilities will be shown as text right below the map.

